name: Continuous integration
on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    name: Complete test suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2.2.1
      - run: cargo check --all-features
      - run: cargo check --no-default-features
      - run: cargo test
      - run: cargo fmt --all -- --check
      - run: cargo clippy -- -W clippy::pedantic -W clippy::cargo
